:: It seems required to run this script as administrator because that seems required from symlinking.

set "path=C:\Program Files (x86)\World of Warcraft"

if exist "%path%\_retail_" (
  if not exist "%path%\_retail_\Interface" mkdir "%path%\_retail_\Interface"
  if not exist "%path%\_retail_\Interface\AddOns" mkdir "%path%\_retail_\Interface\AddOns"
  mklink /D "%path%\_retail_\Interface\AddOns\Array" "%~dp0\AddOns\Array"
  mklink /D "%path%\_retail_\Interface\AddOns\Bags" "%~dp0\AddOns\Bags"
  mklink /D "%path%\_retail_\Interface\AddOns\Boolean" "%~dp0\AddOns\Boolean"
  mklink /D "%path%\_retail_\Interface\AddOns\Caching" "%~dp0\AddOns\Caching"
  mklink /D "%path%\_retail_\Interface\AddOns\CommoditiesBuyer" "%~dp0\AddOns\CommoditiesBuyer"
  mklink /D "%path%\_retail_\Interface\AddOns\CommodityBuyerAndSeller" "%~dp0\AddOns\CommodityBuyerAndSeller"
  mklink /D "%path%\_retail_\Interface\AddOns\CommunityFeastHandler" "%~dp0\AddOns\CommunityFeastHandler"
  mklink /D "%path%\_retail_\Interface\AddOns\Compatibility" "%~dp0\AddOns\Compatibility"
  mklink /D "%path%\_retail_\Interface\AddOns\Conditionals" "%~dp0\AddOns\Conditionals"
  mklink /D "%path%\_retail_\Interface\AddOns\Coroutine" "%~dp0\AddOns\Coroutine"
  mklink /D "%path%\_retail_\Interface\AddOns\Events" "%~dp0\AddOns\Events"
  mklink /D "%path%\_retail_\Interface\AddOns\Float" "%~dp0\AddOns\Float"
  mklink /D "%path%\_retail_\Interface\AddOns\Function" "%~dp0\AddOns\Function"
  mklink /D "%path%\_retail_\Interface\AddOns\Hook" "%~dp0\AddOns\Hook"
  mklink /D "%path%\_retail_\Interface\AddOns\Hooking" "%~dp0\AddOns\Hooking"
  mklink /D "%path%\_retail_\Interface\AddOns\Library" "%~dp0\AddOns\Library"
  mklink /D "%path%\_retail_\Interface\AddOns\Lua" "%~dp0\AddOns\Lua"
  mklink /D "%path%\_retail_\Interface\AddOns\Mathematics" "%~dp0\AddOns\Mathematics"
  mklink /D "%path%\_retail_\Interface\AddOns\MoneyMakingAssistant" "%~dp0\AddOns\MoneyMakingAssistant"
  mklink /D "%path%\_retail_\Interface\AddOns\Object" "%~dp0\AddOns\Object"
  mklink /D "%path%\_retail_\Interface\AddOns\Resolvable" "%~dp0\AddOns\Resolvable"
  mklink /D "%path%\_retail_\Interface\AddOns\Scheduling" "%~dp0\AddOns\Scheduling"
  mklink /D "%path%\_retail_\Interface\AddOns\Serialization" "%~dp0\AddOns\Serialization"
  mklink /D "%path%\_retail_\Interface\AddOns\Set" "%~dp0\AddOns\Set"
  mklink /D "%path%\_retail_\Interface\AddOns\Stoppable" "%~dp0\AddOns\Stoppable"
  mklink /D "%path%\_retail_\Interface\AddOns\String" "%~dp0\AddOns\String"
  mklink /D "%path%\_retail_\Interface\AddOns\Tooltips" "%~dp0\AddOns\Tooltips"
  mklink /D "%path%\_retail_\Interface\AddOns\Yielder" "%~dp0\AddOns\Yielder"
)
